# Generated by Django 4.1.7 on 2023-10-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the question for the flashcard')),
                ('image', models.ImageField(blank=True, help_text='Upload an image if needed', null=True, upload_to='flashcards/images/')),
                ('file', models.FileField(blank=True, help_text='Upload a file if needed', null=True, upload_to='flashcards/files/')),
                ('answer_text', models.TextField(blank=True, help_text='Enter the text answer for the flashcard', null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='flashcards', to='cards.tag')),
            ],
        ),
    ]
